import { Message } from 'discord.js';
import { getVoiceConnection, createAudioPlayer, createAudioResource, StreamType } from '@discordjs/voice';
import { join } from 'path';
import { existsSync, readFileSync, writeFileSync, unlinkSync } from 'fs';
import { tmpdir } from 'os';

const SOUND_MAP: { [key: string]: string } = {
	'!': 'se.wav',
	'?': 'se2.wav',
	'/': 'se3.wav',
	'-': 'se4.wav'
};

export class SoundSequencer {
	private soundPaths: { [key: string]: string };
	public useSynthesis: boolean = true;

	constructor() {
		this.soundPaths = {};
		for (const key in SOUND_MAP) {
			this.soundPaths[key] = join(__dirname, '../../assets/', SOUND_MAP[key]);
		}
	}

	public async processMessage(message: Message): Promise<void> {
		if (message.author.bot) return;
		if (!message.guild) return;

		// Sequence regex: anything containing brackets
		console.log('Processing message for sound sequencing:', message.content);
		if (message.content.includes('[') && message.content.includes(']')) {
			await this.handleSequence(message);
			return;
		}

		// Simple/Legacy regex: prefix BPM or just exclamation marks
		// Updated to allow mixed ! ? . , _ -
		const match = message.content.match(/^(\d+)?([!?.,\/\-]+)$/);
		if (match) {
			await this.handleSimple(message, match);
			return;
		}
	}

	private async handleSequence(message: Message): Promise<void> {
		if (!this.checkVoiceConnection(message)) return;

		const tracks = message.content.split('&&');
		const schedule: { delay: number; symbol: string }[] = [];

		for (const track of tracks) {
			// Update regex to allow () and digits inside []
			const matches = Array.from(track.matchAll(/(\d+)?\s*\[([^\]]+)\]/g));
			if (matches.length === 0) continue;

			let currentTime = 0;

			for (const match of matches) {
				const bpmStr = match[1];
				const rawMarks = match[2];

				// Expand loops: 2(!!) -> !!!!
				const marks = this.expandLoops(rawMarks);

				let interval = 400; // default 150 BPM
				if (bpmStr) {
					const bpm = parseInt(bpmStr, 10);
					if (bpm > 0) {
						interval = 60000 / bpm;
					}
				}

				const count = marks.length;
				for (let i = 0; i < count; i++) {
					const char = marks[i];
					if (char === '.') {
						// Quarter rest
						currentTime += interval;
					} else if (char === ',') {
						// Eighth rest
						currentTime += interval / 2;
					} else if (SOUND_MAP[char]) {
						// Sound
						schedule.push({ delay: currentTime, symbol: char });
						currentTime += interval;
					}
					// Ignore other characters (newlines, spaces, etc generated by expansion or user input)
				}
			}
		}

		if (schedule.length === 0) return;

		// Sort by delay for better visual debugging (optional)
		schedule.sort((a, b) => a.delay - b.delay);

		if (this.useSynthesis) {
			this.playMixedSound(message, schedule);
		} else {
			this.playSimpleSound(message, schedule);
		}
	}

	private expandLoops(input: string): string {
		let result = input;
		// Recursively match N(...) pattern
		// Regex: digit(content with no parenthesis)
		const loopRegex = /(\d+)\(([^()]+)\)/;

		let match = result.match(loopRegex);
		while (match) {
			const count = parseInt(match[1], 10);
			const content = match[2];
			const expanded = content.repeat(count);

			// Replace the first match with expanded content
			result = result.replace(match[0], expanded);

			// Check again for nested or subsequent loops
			match = result.match(loopRegex);
		}
		return result;
	}

	private async handleSimple(message: Message, match: RegExpMatchArray): Promise<void> {
		if (!this.checkVoiceConnection(message)) return;

		const bpmStr = match[1];
		const marks = match[2];

		let interval = 400; // default 150 BPM
		if (bpmStr) {
			const bpm = parseInt(bpmStr, 10);
			if (bpm > 0) {
				interval = 60000 / bpm;
			}
		}

		const count = marks.length;
		const schedule: { delay: number; symbol: string }[] = [];
		let currentTime = 0;

		for (let i = 0; i < count; i++) {
			const char = marks[i];
			if (char === '.') {
				currentTime += interval;
			} else if (char === ',') {
				currentTime += interval / 2;
			} else {
				schedule.push({ delay: currentTime, symbol: char });
				currentTime += interval;
			}
		}

		if (this.useSynthesis) {
			this.playMixedSound(message, schedule);
		} else {
			this.playSimpleSound(message, schedule);
		}
	}

	private playSimpleSound(message: Message, schedule: { delay: number; symbol: string }[]) {
		if (!message.guild) return;
		const connection = getVoiceConnection(message.guild.id);
		if (!connection) return;

		try {
			const player = createAudioPlayer();
			connection.subscribe(player);

			console.log(`Playing simple sequence (No synth) with ${schedule.length} notes for ${message.author.tag}`);

			schedule.forEach(({ delay, symbol }) => {
				const soundPath = this.soundPaths[symbol];
				if (!soundPath || !existsSync(soundPath)) {
					console.warn(`Sound file not found for symbol ${symbol}:`, soundPath);
					return;
				}

				setTimeout(() => {
					const resource = createAudioResource(soundPath);
					player.play(resource);
				}, delay);
			});
		} catch (error) {
			console.error('Failed to play simple sound sequence:', error);
		}
	}

	private playMixedSound(message: Message, schedule: { delay: number; symbol: string }[]) {
		if (!message.guild) return;
		const connection = getVoiceConnection(message.guild.id);
		if (!connection) return;

		try {
			// Pre-load all required audio buffers
			const loadedBuffers: { [key: string]: { buffer: Buffer; sampleRate: number; numChannels: number; bitsPerSample: number } } = {};

			// Load unique symbols
			const uniqueSymbols = Array.from(new Set(schedule.map(s => s.symbol)));

			for (const symbol of uniqueSymbols) {
				const soundPath = this.soundPaths[symbol];
				if (!soundPath || !existsSync(soundPath)) {
					console.warn(`Sound file not found for symbol ${symbol}:`, soundPath);
					continue;
				}

				const wavBuffer = readFileSync(soundPath);
				console.log(`[DEBUG] Read WAV file for ${symbol}: ${soundPath}, size: ${wavBuffer.length}`);

				// Find 'fmt ' chunk
				let fmtOffset = 12;
				let foundFmt = false;
				while (fmtOffset < wavBuffer.length) {
					const chunkId = wavBuffer.toString('utf8', fmtOffset, fmtOffset + 4);
					const chunkSize = wavBuffer.readUInt32LE(fmtOffset + 4);
					if (chunkId === 'fmt ') {
						foundFmt = true;
						break;
					}
					// Chunks must be word-aligned
					fmtOffset += 8 + chunkSize + (chunkSize % 2);
				}

				if (!foundFmt) {
					console.error(`[DEBUG] fmt chunk not found in ${soundPath}`);
					continue;
				}

				const audioFormat = wavBuffer.readUInt16LE(fmtOffset + 8);
				const numChannels = wavBuffer.readUInt16LE(fmtOffset + 8 + 2);
				const sampleRate = wavBuffer.readUInt32LE(fmtOffset + 8 + 4);
				const bitsPerSample = wavBuffer.readUInt16LE(fmtOffset + 8 + 14);

				console.log(`[DEBUG] FMT for ${symbol}: Format=${audioFormat}, Ch=${numChannels}, Rate=${sampleRate}, Bits=${bitsPerSample}`);

				// Find 'data' chunk
				let dataOffset = 12;
				let foundData = false;

				while (dataOffset < wavBuffer.length) {
					const chunkId = wavBuffer.toString('utf8', dataOffset, dataOffset + 4);
					const chunkSize = wavBuffer.readUInt32LE(dataOffset + 4);

					if (chunkId === 'data') {
						foundData = true;
						break;
					}
					// Chunks must be word-aligned
					dataOffset += 8 + chunkSize + (chunkSize % 2);
				}

				if (!foundData) {
					console.error(`[DEBUG] data chunk not found in ${soundPath}`);
					continue;
				}

				const dataSize = wavBuffer.readUInt32LE(dataOffset + 4);
				const rawAudioData = wavBuffer.subarray(dataOffset + 8, dataOffset + 8 + dataSize);

				// Normalize to 16-bit PCM
				const normalizedData = this.normalizeTo16Bit(rawAudioData, audioFormat, bitsPerSample);

				if (!normalizedData) {
					console.error(`[DEBUG] Failed to normalize audio for ${symbol}`);
					continue;
				}

				loadedBuffers[symbol] = {
					buffer: normalizedData,
					sampleRate,
					numChannels,
					bitsPerSample: 16 // Always 16 after normalization
				};
			}

			if (Object.keys(loadedBuffers).length === 0) {
				console.error('No valid audio assets loaded.');
				return;
			}

			// Use the first symbol's format as master format
			const masterSymbol = schedule.find(s => loadedBuffers[s.symbol])?.symbol;
			if (!masterSymbol) return;

			const masterFmt = loadedBuffers[masterSymbol];
			console.log(`[DEBUG] Master format from ${masterSymbol}: Rate=${masterFmt.sampleRate}, Ch=${masterFmt.numChannels}`);

			// Calculate total duration
			const bytesPerMs = (masterFmt.sampleRate * masterFmt.numChannels * 2) / 1000; // 16-bit = 2 bytes
			const blockAlign = masterFmt.numChannels * 2;

			let maxDurationMs = 0;
			for (const note of schedule) {
				const buf = loadedBuffers[note.symbol];
				if (!buf) continue;
				const durationMs = (buf.buffer.length / (buf.sampleRate * buf.numChannels * 2)) * 1000;
				const endMs = note.delay + durationMs;
				if (endMs > maxDurationMs) maxDurationMs = endMs;
			}

			const totalBufferBytes = Math.ceil((maxDurationMs + 100) * bytesPerMs);
			const alignedTotalBytes = Math.ceil(totalBufferBytes / blockAlign) * blockAlign;

			console.log(`[DEBUG] Mixing audio. Duration: ${maxDurationMs.toFixed(2)}ms, Buffer: ${alignedTotalBytes}`);

			const outputBuffer = Buffer.alloc(alignedTotalBytes);

			// Mix
			let clipsMixed = 0;
			for (const note of schedule) {
				const src = loadedBuffers[note.symbol];
				if (!src) continue;

				// Warn if format mismatch
				if (src.sampleRate !== masterFmt.sampleRate) {
					console.warn(`[WARN] Sample rate mismatch: ${note.symbol} (${src.sampleRate}) vs Master (${masterFmt.sampleRate}). Pitch will be wrong.`);
				}

				const offsetMs = note.delay;
				const startByte = Math.floor(offsetMs * bytesPerMs);
				const alignedStartByte = Math.floor(startByte / blockAlign) * blockAlign;

				for (let i = 0; i < src.buffer.length; i += 2) {
					const destIndex = alignedStartByte + i;
					if (destIndex + 1 >= outputBuffer.length) break;

					const existingSample = outputBuffer.readInt16LE(destIndex);
					const newSample = src.buffer.readInt16LE(i);

					let mixed = existingSample + newSample;
					if (mixed > 32767) mixed = 32767;
					if (mixed < -32768) mixed = -32768;

					outputBuffer.writeInt16LE(mixed, destIndex);
				}
				clipsMixed++;
			}
			console.log(`[DEBUG] Mixed ${clipsMixed} clips.`);

			// Construct Header
			const header = Buffer.alloc(44);
			header.write('RIFF', 0);
			header.writeUInt32LE(36 + outputBuffer.length, 4);
			header.write('WAVE', 8);
			header.write('fmt ', 12);
			header.writeUInt32LE(16, 16);
			header.writeUInt16LE(1, 20); // PCM
			header.writeUInt16LE(masterFmt.numChannels, 22);
			header.writeUInt32LE(masterFmt.sampleRate, 24);
			header.writeUInt32LE(masterFmt.sampleRate * blockAlign, 28); // ByteRate
			header.writeUInt16LE(blockAlign, 32);
			header.writeUInt16LE(16, 34); // BitsPerSample
			header.write('data', 36);
			header.writeUInt32LE(outputBuffer.length, 40);

			const finalBuffer = Buffer.concat([header, outputBuffer]);

			const tempPath = join(tmpdir(), `crok_${Date.now()}.wav`);
			writeFileSync(tempPath, finalBuffer);
			console.log(`[DEBUG] Wrote to: ${tempPath}`);

			const player = createAudioPlayer();
			const resource = createAudioResource(tempPath);

			connection.subscribe(player);
			player.play(resource);

			setTimeout(() => {
				try { unlinkSync(tempPath); } catch (e) { }
			}, maxDurationMs + 5000);

		} catch (error) {
			console.error('Failed to play sound sequence:', error);
		}
	}

	private normalizeTo16Bit(buffer: Buffer, audioFormat: number, bitsPerSample: number): Buffer | null {
		// Output is always 16-bit PCM
		if (audioFormat === 1 && bitsPerSample === 16) {
			return buffer; // Already 16-bit PCM
		}

		console.log(`[DEBUG] Normalizing from Format=${audioFormat}, Bits=${bitsPerSample} to 16-bit PCM`);

		try {
			// 8-bit PCM (unsigned)
			if (audioFormat === 1 && bitsPerSample === 8) {
				const newBuffer = Buffer.alloc(buffer.length * 2);
				for (let i = 0; i < buffer.length; i++) {
					const val = buffer.readUInt8(i); // 0-255
					const val16 = (val - 128) * 256;
					newBuffer.writeInt16LE(val16, i * 2);
				}
				return newBuffer;
			}

			// 24-bit PCM (signed)
			if (audioFormat === 1 && bitsPerSample === 24) {
				const numSamples = buffer.length / 3;
				const newBuffer = Buffer.alloc(numSamples * 2);
				for (let i = 0; i < numSamples; i++) {
					const b0 = buffer[i * 3];
					const b1 = buffer[i * 3 + 1];
					const b2 = buffer[i * 3 + 2];
					let val = (b2 << 16) | (b1 << 8) | b0;
					if (val & 0x800000) val |= 0xFF000000; // Sign extend if negative
					const val16 = val >> 8;
					newBuffer.writeInt16LE(val16, i * 2);
				}
				return newBuffer;
			}

			// 32-bit Float (IEEE 754)
			if (audioFormat === 3 && bitsPerSample === 32) {
				const numSamples = buffer.length / 4;
				const newBuffer = Buffer.alloc(numSamples * 2);
				for (let i = 0; i < numSamples; i++) {
					const val = buffer.readFloatLE(i * 4);
					const clamped = Math.max(-1, Math.min(1, val));
					const val16 = Math.floor(clamped * 32767);
					newBuffer.writeInt16LE(val16, i * 2);
				}
				return newBuffer;
			}

			// 32-bit Int (PCM)
			if (audioFormat === 1 && bitsPerSample === 32) {
				const numSamples = buffer.length / 4;
				const newBuffer = Buffer.alloc(numSamples * 2);
				for (let i = 0; i < numSamples; i++) {
					const val = buffer.readInt32LE(i * 4);
					const val16 = val >> 16;
					newBuffer.writeInt16LE(val16, i * 2);
				}
				return newBuffer;
			}

			console.warn(`[WARN] Unsupported format: Format=${audioFormat}, Bits=${bitsPerSample}`);
			return null;

		} catch (e) {
			console.error('Normalization error:', e);
			return null;
		}
	}

	private checkVoiceConnection(message: Message): boolean {
		if (!message.guild) return false;

		const connection = getVoiceConnection(message.guild.id);
		if (!connection) return false;

		const member = message.member;
		if (!member?.voice.channelId) return false;
		if (connection.joinConfig.channelId !== member.voice.channelId) return false;

		return true;
	}
}

export const soundSequencer = new SoundSequencer();
